[project]
name = "FashionStore"
version = "0.1.0"
authors = [
    #may be later
]
description = "Project for store of fashion clothing."
dependencies = 'requirements.txt'
readme = 'README.md'

[project.urls]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"