DROP TABLE IF EXISTS user;
-- DROP TABLE IF EXISTS favourites


CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);